spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://localhost:3306/mango
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


jwt:
  issuer: mango@naver.com
  secret_key: mango-springboot

